[develop]
script_dir=$base/lib/nav24r
[install]
install_scripts=$base/lib/nav24r

[metadata]
name = nav24r
version = 2.0.0
description = NAV24R - 人形机器人导航系统
maintainer = NAV24R Team
maintainer_email = nav24r-maintainer@users.noreply.github.com
license = MIT

[options]
packages = find:
install_requires =
    pyyaml
    setuptools
